-- 모회사 칸을 더한다.
--
-- 회사명이 한 칸이라 두 사실이 겹쳐 앉아 있었다. 삼성 채용 사이트 하나에 삼성SDS 와 삼성전기
-- 공고가 섞여 들어오는데, 목록이 회사명을 주지 않는 사이트(토스·우아한형제들)에서는 같은 칸에
-- 운영자가 적어 둔 상위 기업 이름이 들어갔다. 소비 측이 그 칸 하나를 보고 "이것이 공고를 낸
-- 회사인가, 그 그룹인가" 를 가릴 방법이 없었다 (`.claude/tasks/todo/prd-fields-and-logo.md`).
--
-- 두 칸으로 가른다.
--
-- | 칸 | 무엇이 들어오나 | 빌 수 있나 |
-- |---|---|---|
-- | `parent_company` | `crawlers.default_company`, 없으면 크롤러 이름 | 사실상 없다. `crawlers.name` 이 NOT NULL 이다 |
-- | `company` | 공고에서 뽑은 회사명 그대로 | 빈다. 사이트가 회사명을 주지 않으면 NULL 이다 |
--
-- **자회사 칸을 모회사 이름으로 채우지 않는다.** 채우면 두 칸이 같은 값이 되어, 계열사를
-- 가르려고 칸을 늘린 일이 없던 일이 된다. 자회사가 비어 있다는 것은 "이 사이트는 계열사를
-- 말하지 않는다" 는 사실이고, 그 사실이 값으로 남아야 한다.
--
-- `parent_company` 에는 정규화 규칙을 태우지 않는다. 운영자가 크롤러에 적은 값을 그대로 옮기는
-- 칸이라 `app/normalize/rules.py` 의 `NORMALIZED_FIELDS` 에 넣지 않고, 그래서 화면에서 이 칸에
-- 규칙을 만들려 하면 `unknown_field` 로 거절된다.
--
-- 두 표는 건드리지 않았고, 그것이 판단이다.
--
-- | 표 | 왜 그대로인가 |
-- |---|---|
-- | `job_classifications` | 분류가 내는 값이 아니다. 회사명은 본문 판독으로 정할 것이 아니라 크롤러가 아는 사실이다 |
-- | `job_field_overrides` 의 CHECK | 공고 한 건씩 고칠 값이 아니다. 모회사가 틀렸으면 `crawlers.default_company` 를 고치고 재정규화하면 그 크롤러의 전부가 함께 고쳐진다 |
--
-- `company_source` 는 이제 할 말이 없다 — 어느 출처인지가 칸 이름으로 드러난다. 그러나 그
-- 컬럼을 지우는 것은 **다음 마이그레이션(0019)** 이다. 컬럼을 더하는 것은 DB 가 코드보다
-- 넓어질 뿐이라 아무것도 깨지 않지만(0017 이 같은 이유로 코드를 다음 커밋에서 넓혔다), 지우는
-- 것은 그 컬럼에 쓰는 코드가 손을 놓은 뒤여야 한다. 여기서 함께 지우면 `insert_normalized` 가
-- 없는 컬럼에 쓰게 되어 그 순간 정규화가 한 건도 되지 않는다.
--
-- 적용 직후 `parent_company` 는 기존 행 전부에서 NULL 이다. 값은 재정규화를 돌려야 들어온다 —
-- 이 파일에 `normalized_jobs` 를 대상으로 하는 UPDATE 가 없다. 재크롤링은 필요 없다. 값의
-- 출처가 `crawlers` 라 `raw_jobs` 를 다시 읽을 일이 아니기 때문이다.
--
-- 되돌리기: `migrate down` 이 컬럼 하나를 지운다. 사라지는 것은 모회사 값뿐이고, 그 값은
-- `crawlers` 에 그대로 있으므로 다시 적용하고 재정규화하면 같은 값이 돌아온다.

-- migrate:up
ALTER TABLE normalized_jobs ADD COLUMN parent_company TEXT;

-- migrate:down
ALTER TABLE normalized_jobs DROP COLUMN parent_company;
